name: Django CI

on:
  push:
    branches: [ci-setup]
  pull_request:
    branches: [ci-setup]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 300501
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SECRET_KEY: 'ci-test-secret-key'
      DEBUG: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Cambiamos el working-directory a backend
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        working-directory: backend
        run: python manage.py migrate

      - name: Run tests
        working-directory: backend
        run: python manage.py test

      # 5. Ejecutar tests
      - name: Run tests
        run: python backend/manage.py test



