name: Django CI

on:
  push:
    branches: [ ci-setup ]
  pull_request:
    branches: [ ci-setup ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Hacer checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # 4. Ejecutar migraciones (opcional si las tienes en tests)
    - name: Apply migrations
      run: |
        python backend/manage.py migrate

    # 5. Ejecutar tests
    - name: Run tests
      run: |
        python backend/manage.py test
