name: Django CI

on:
  push:
    branches: [ ci-setup ]
  pull_request:
    branches: [ ci-setup ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 300501
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SECRET_KEY: 'ci-test-secret-key'
      DEBUG: '1'

    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # Ejecutar migraciones
    - name: Apply migrations
      run: |
        python backend/manage.py migrate

    # Ejecutar tests
    - name: Run tests
      run: |
        python backend/manage.py test

