name: Django CI

on:
  push:
    branches: [ci-setup]
  pull_request:
    branches: [ci-setup]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 300501
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SECRET_KEY: 'ci-test-secret-key'
      DEBUG: '1'
      DATABASE_URL: 'postgres://postgres:300501@localhost:5432/ecommerce_db'

    steps:
    # 1. Checkout code
    - uses: actions/checkout@v3

    # 2. Set up Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # 4. Apply migrations
    - name: Apply migrations
      run: |
        python backend/manage.py migrate

    # 5. Run tests
    - name: Run tests
      run: |
        python backend/manage.py test

